# Generated by Django 4.1.2 on 2022-11-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial_api', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial_api.todo'),
        ),
    ]
